### ISSUE TITLE
[어드민] 게시글 관리 페이지 구현

### ISSUE THREAD

**Issue by newbe01** [newbe01/4study-admin#30]
준비한 테스트를 토대로, 게시글 관리 페이지를 구현한다

#TODO
* [x] 게시판 프로젝트
  * [x] https://github.com/newbe01/4study/issues/81
  * [x] Data REST API 설정 검토하기
  * [x] 테스트용 계정 추가하기
* [x]  게시글, 댓글 상세 내용을 보기 위한 모달(Modal) 추가
* [x] 기본 에러 페이지 구현
